language: php

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=weak

git:
    depth: 10

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: 8.0
      before_install:
        - composer req --dev league/uri-components:2.x-dev omnipay/common:3.0.x-dev
    - php: 7.2
      env:
        - COMPOSER_FLAGS="--prefer-lowest --prefer-stable"

before_install:
    - composer global require --no-progress --no-scripts --no-plugins symfony/flex

install:
    - composer update $COMPOSER_FLAGS

script:
    - bin/phpunit

notifications:
  email:
    - payumsupport@forma-pro.com
